apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/cert-manager-crds.yaml
  - namespace.yaml
  - secret-sealed.yaml
  - helm-repo.yaml
  - helm-release.yaml
  - cluster-issuer.yaml
