apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
  labels:
    app: vaultwarden
data:
  # ROCKET_PORT: "80"
  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "false"
  # DOMAIN: "https://vaultwarden.example.com"
  # SIGNUPS_ALLOWED: "true"
  # WEBSOCKET_ENABLED: "true"
