apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - configmap.yaml
  - secret-sealed.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
