---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: faris-protoflio
  namespace: faris-protoflio
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: ./clusters/production/faris/protoflio
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: calver
  namespace: faris-protoflio
spec:
  filterTags:
    extract: $1
    pattern: ^([0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]{4})$
  imageRepositoryRef:
    name: faris-protoflio
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: faris-protoflio
  namespace: faris-protoflio
spec:
  image: ghcr.io/faris193/protoflio
  interval: 1m0s
  secretRef:
    name: ghcr-secret
