apiVersion: v1
kind: Service
metadata:
  name: faris-protoflio-service
  namespace: faris-protoflio
spec:
  selector:
    app: faris-protoflio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
