apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  selector:
    app: frigate
  ports:
    - name: web-with-auth
      port: 8971
      targetPort: 8971
    - name: web-no-auth
      port: 5000
      targetPort: 5000
  type: ClusterIP
