apiVersion: v1
kind: Service
metadata:
  name: faris-website-service
  namespace: faris-website
spec:
  selector:
    app: faris-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
