apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs
  namespace: rustfs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: "s3.malrusayni.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs-service
                port:
                  number: 9000
  tls:
    - hosts:
        - "s3.malrusayni.com"
      secretName: rustfs-tls
