apiVersion: v1
kind: Service
metadata:
  name: rustfs-service
  namespace: rustfs
spec:
  selector:
    app: rustfs
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
