apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfo-website-deployment
  namespace: kfo-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfo-website
  template:
    metadata:
      labels:
        app: kfo-website
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: kfo-website
          image: ghcr.io/kfo-solutions/website:2026.03.01.0201 # {"$imagepolicy": "kfo-website:kfo-website"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
