apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kfo-website
  namespace: kfo-website
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: "next.kfosolutions.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kfo-website-service
                port:
                  number: 8080
  tls:
    - hosts:
        - "next.kfosolutions.com"
      secretName: kfo-website-tls
