apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-secret-sealed.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
  - image-repo.yaml
  - image-policy.yaml
  - image-automation.yaml
