apiVersion: v1
kind: Service
metadata:
  name: kfo-website-service
  namespace: kfo-website
spec:
  selector:
    app: kfo-website
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
